### ISSUE TITLE
Desktop icon seems to be missing

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/org.gnome.SoundRecorder#2]
Desktop icon of the GNOME Sound Recorder seems to be missing or broken.

![Sound Recorder - missing icon](https://user-images.githubusercontent.com/2339930/47915704-fd916580-dea3-11e8-9b27-6d8cd96e5073.png)

**Comment by felipeborges** [comment]
I have proposed a merge request upstream for this. I will update sound recorder here once it gets merged.
